"""add refresh_jti to users

Revision ID: 3c8c68b3410f
Revises: 24f12dde8994
Create Date: 2026-09-23 14:24:51.158042
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3c8c68b3410f'
down_revision: str | None = '24f12dde8994'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_jti', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_jti')
    # ### end Alembic commands ###
